Add initial Finnish translation (credit: LINUX-SAUNA)
Syncplay/syncplay pull request #561
Opened 2022-11-03 19:50 UTC by Et0h

2022-11-05 13:41 UTC, Mikaela requested changes
I think a lot of this translation is strange or has mistakes even in easier to translate spots, but it's difficult to comment without having the original side by side. I provided some examples in the review that instantly hit my eyes without scrolling that far down.

For example the Windows NSIS installer bothers me as "shortcuts" have been "pikakuvakkeet" as far as I can remember, while the translation introduces a new term that is not an established part of Finnish localization.

See also: https://github.com/tchx84/Flatseal/pull/497 from the same author while I find the comments there upsetting and discouraging from localizing Finnish in general and also in poor taste for being in Finnish that is not established language of the project.

2022-11-05 13:41 UTC, Mikaela commented on syncplay/messages_fi.py
> +     "installer-shortcut": "Luo oikopolut seuraaviin kohteisiin:",
```suggestion
     "installer-shortcut": "Luo pikakuvakkeet kohteisiin:",
```

2022-11-05 13:41 UTC, Mikaela commented on syncplay/messages_fi.py
> +     "relative-config-notification": "Asiaankuuluva asetustiedosto(t) ladattu: {}",
I think this is somewhat clumsy way to express this, if it's "asetustiedosto(t)", shouldn't it also be "Asiaankuuluva(t)"?

2022-11-05 13:41 UTC, Mikaela commented on syncplay/messages_fi.py
> +     "fastforward-notification": "Pikakelaus eteenpäin koska ilmeni aikaero {}",  # User
using the word "koska" ("because") requires a comma and I think these would be better expressed:

```suggestion
     "rewind-notification": "Kelattiin taaksepäin aikaeron {} vuoksi",  # User
     "fastforward-notification": "Pikakelattiin eteenpäin aikaeron {} vuoksi",  # User
```

2022-11-05 16:05 UTC, Et0h commented
> I think a lot of this translation is strange or has mistakes even in easier to translate spots, but it's difficult to comment without having the original side by side. 

@Mikaela I see how it can be difficult to compare the translation with the English. As such, I've now created a script for messages.py to print the messages in multiple languages and have run it it to English/Finnish to support comparison. See [Finnish Translation Comparison (Original).txt](https://github.com/Syncplay/syncplay/files/9944207/Finnish.Translation.Comparison.Original.txt) for the results.

The code I wrote was:
```
def printLanguages(languages):
    languageNames = []
    for language in languages:
        languageNames.append(messages[language]["LANGUAGE"])
    comparison = "Comparing the following languages: {}\n".format(", ".join(languageNames))
    for message in messages["en"]:
        comparison = comparison + "[{}]\n".format(message)
        for language in languages:
            languageName = messages[language]["LANGUAGE"]
            messageText = messages[language][message] if message in messages[language] else "<UNTRANSLATED>"
            comparison = comparison + "{}: {}\n".format(languageName, messageText)
        comparison = comparison + "\n"
    return comparison

print(printLanguages(["en","fi"]))
```

2022-11-06 14:08 UTC, heidiwenger commented on syncplay/messages_fi.py
> +     "relative-config-notification": "Asiaankuuluva asetustiedosto(t) ladattu: {}",
These are minor mistakes, so why can't you just correct them when spotted? All this is cooperative work.

2022-11-06 14:11 UTC, heidiwenger commented on syncplay/messages_fi.py
> +     "fastforward-notification": "Pikakelaus eteenpäin koska ilmeni aikaero {}",  # User
So go ahead? I think this translation should be gotten in and into polishing it all the time, then.

2022-11-06 14:22 UTC, Mikaela reviewed
I am working on attempting to improve this translator in #563, but I am not able to focus on it 24/7 nor am I able to do it all in one go or give any timeline schedules.

2022-11-06 14:22 UTC, Mikaela commented on syncplay/messages_fi.py
> +     "relative-config-notification": "Asiaankuuluva asetustiedosto(t) ladattu: {}",
#563

2022-11-06 14:22 UTC, Mikaela commented on syncplay/messages_fi.py
> +     "fastforward-notification": "Pikakelaus eteenpäin koska ilmeni aikaero {}",  # User
#563

2022-11-06 15:32 UTC, karpse commented
> I think a lot of this translation is strange or has mistakes even in easier to translate spots, but it's difficult to comment without having the original side by side. I provided some examples in the review that instantly hit my eyes without scrolling that far down.
> 
> For example the Windows NSIS installer bothers me as "shortcuts" have been "pikakuvakkeet" as far as I can remember, while the translation introduces a new term that is not an established part of Finnish localization.
> 
> See also: [tchx84/Flatseal#497](https://github.com/tchx84/Flatseal/pull/497) from the same author while I find the comments there upsetting and discouraging from localizing Finnish in general and also in poor taste for being in Finnish that is not established language of the project.

Be that as it may, I don't think the translation of this author(s?) can be merged without checking it thoroughly. I looked other translations by this [LINUX-SAUNA](https://github.com/LINUX-SAUNA) GitHub user and it seems that his way of translating is, well, peculiar. And despite the feedback, the translation style does not seem to have changed in this translation.

My previous examples already tell enough, LINUX-SAUNA translated "documentation" -> "selonteko", "permissions" -> "luvitus", "syscall" -> "järjestelmäkäsky" (established term is "järjestelmäkutsu" and "käsky" is technically incorrect, because the userland program cannot "käskeä" kernel, it "kutsuu" or "pyytää"), handling the D-Bus vocabulary carelessly and translated "xdg-pictures" -> "xdg-kuvat" which is a variable that has no translation and really shouldn't be translated. I think that the user is excited about her/his new hobby and wants to renew the vocabulary, but it doesn't work if there is no IT expertise. In addition to this, I also saw some careless mistakes.

2022-11-08 00:07 UTC, heidiwenger commented on syncplay/messages_fi.py
> +     "relative-config-notification": "Asiaankuuluva asetustiedosto(t) ladattu: {}",
> > These are minor mistakes, so why can't you just correct them when spotted? All this is cooperative work.
> 
> As far as I can see, you have not been involved in making these translations (or Flatseal translations). You have only commented on either misinformation or tried to label the problems presented by others in translations as "minor". Stop the bothering, it's starting to feel like you're just a LINUX-SAUNA alt user.

Excuse me? To request a correction upon finding a mistake with minor thing such as brackets is bothering? What is with that strange offensive attitude of yours. 

The base work is done and mistakes are to be corrected, just as usual. For your information, LINUX-SAUNA is a little community that helps new comers on Linux and also does occasional translations to projects where there is 0% Finnish such as this project. Not professional translators. I did couple of sections on this one too, so.

I think you're taking this too emotionally.

2022-11-09 20:07 UTC, karpse commented on syncplay/messages_fi.py
> +     "relative-config-notification": "Asiaankuuluva asetustiedosto(t) ladattu: {}",
>>> These are minor mistakes, so why can't you just correct them when spotted? All this is cooperative work.
>>
>>As far as I can see, you have not been involved in making these translations (or Flatseal translations). You have only commented on either misinformation or tried to label the problems presented by others in translations as "minor". Stop the bothering, it's starting to feel like you're just a LINUX-SAUNA alt user.
>
>Excuse me? To request a correction upon finding a mistake with minor thing such as brackets is bothering? What is with that strange offensive attitude of yours.

You can translate it however you want, but this and the Flatsea'sl issue show how you repeatedly downplay the massive errors in the translation, which the majority of those who participated in the discussion have acknowledged. Please, just stop it.

>The base work is done and mistakes are to be corrected, just as usual.

Where does this appear? You have not corrected obvious translation errors, but you are trying to include it in the project as it is, or at least you have left all the translation correction work on the shoulders of others. And softwares are not developed in such a way that I add this piece to the software, even though I know it is full of problems and I will (maybe) fix it later. Check out software development and you'll know.

>For your information, LINUX-SAUNA is a little community that helps new comers on Linux and also does occasional translations to projects where there is 0% Finnish such as this project. Not professional translators.

Okay, based on your translations, you are frankly not ready to participate in translation work.

>I did couple of sections on this one too, so.

Source for this?

>I think you're taking this too emotionally.

A matter of opinion, but the truth is still that you should now sit down with your translations, when the level of your translations will be noticed in two projects in one week.

2023-03-11 18:12 UTC, Et0h commented
This translation has now been updated in line with changes provided by @Mikaela.

It would be helpful if someone could check out the updated build for this PR at https://github.com/Syncplay/syncplay/actions/runs/4296941535 and confirm that it works.

2023-03-14 20:41 UTC, merged